# Generated by Django 5.0.1 on 2025-04-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('competitions', models.ManyToManyField(related_name='teams', to='competition.competition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
