# Generated by Django 5.0.1 on 2025-04-09 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0002_initial'),
        ('match', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_matches', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='match.match')),
                ('favorite_competitions', models.ManyToManyField(blank=True, related_name='followed_by', to='competition.competition')),
                ('favorite_teams', models.ManyToManyField(blank=True, related_name='followed_by', to='team.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
